name: "Upload Chart to Bucket"
runs:
  using: "composite"
  steps:
    - name: Load Secrets from Vault
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/optimus-charts-access-key/credentials token | OPTIMUS_CHARTS_ACCESS_KEY ;
          secret/data/github/repo/${{ github.repository }}/optimus-charts-secret-key/credentials token | OPTIMUS_CHARTS_SECRET_KEY ;
          secret/data/github/repo/${{ github.repository }}/chart-dns-invalidator/credentials accessKeyId | AWS_ACCESS_KEY_ID_CACHE_INVALIDATION ;
          secret/data/github/repo/${{ github.repository }}/chart-dns-invalidator/credentials secretAccessKey | AWS_SECRET_ACCESS_KEY_CACHE_INVALIDATION ;
    - name: Upload chart to bucket
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ env.OPTIMUS_CHARTS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ env.OPTIMUS_CHARTS_SECRET_KEY }}
      run: aws s3 cp --recursive ./bin/chart s3://charts.optimus.rancher.io/server-charts
    - name: Invalidate Cloudfront cache
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID_CACHE_INVALIDATION }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY_CACHE_INVALIDATION }}
      run: aws cloudfront create-invalidation --distribution-id ${{ env.CHARTS_DISTRIBUTION_ID }} --paths "/*"
